--계정생성
CREATE USER c##tester2 IDENTIFIED BY 1234 
    DEFAULT TABLESPACE users 
    TEMPORARY TABLESPACE temp 
    PROFILE DEFAULT;
--권한부여    
GRANT CONNECT, RESOURCE TO c##tester2; 
GRANT CREATE VIEW, CREATE SYNONYM TO c##tester2; 
GRANT UNLIMITED TABLESPACE TO c##tester2; 
--락 풀기
ALTER USER c##tester2 ACCOUNT UNLOCK;